apiVersion: v1
kind: Secret
metadata:
  name: video-ad-placement-secrets
  namespace: video-ad-placement
  labels:
    app.kubernetes.io/name: video-ad-placement
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  POSTGRES_PASSWORD: c2VjdXJlcGFzc3dvcmQ=  # securepassword
  REDIS_PASSWORD: cmVkaXNwYXNzd29yZA==    # redispassword
  SECRET_KEY: eW91ci1zZWNyZXQta2V5LWhlcmU=  # your-secret-key-here
  API_TOKEN: eW91ci1hcGktdG9rZW4taGVyZQ==  # your-api-token-here

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: video-ad-placement
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: secrets
type: Opaque
data:
  POSTGRES_DB: dmlkZW9fYWRfcGxhY2VtZW50        # video_ad_placement
  POSTGRES_USER: cG9zdGdyZXM=                  # postgres
  POSTGRES_PASSWORD: c2VjdXJlcGFzc3dvcmQ=      # securepassword

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: video-ad-placement
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: secrets
type: Opaque
data:
  REDIS_PASSWORD: cmVkaXNwYXNzd29yZA==  # redispassword

---
apiVersion: v1
kind: Secret
metadata:
  name: model-registry-secrets
  namespace: video-ad-placement
  labels:
    app.kubernetes.io/name: video-ad-placement
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Model registry credentials (if using private model repositories)
  HUGGINGFACE_TOKEN: ""  # Add base64 encoded HuggingFace token if needed
  MODEL_REGISTRY_USERNAME: ""
  MODEL_REGISTRY_PASSWORD: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: video-ad-placement
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: secrets
type: Opaque
data:
  GRAFANA_ADMIN_PASSWORD: YWRtaW4xMjM=  # admin123 